name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: bluesense
          POSTGRES_PASSWORD: bluesense_pw
          POSTGRES_DB: bluesense_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
      - name: Publish
        run: dotnet publish Bluesense/Bluesense.csproj -c Release -o out
      - name: Build Docker image
        run: docker build -f Bluesense/Dockerfile -t bluesense-api:latest .
      # - name: Push Docker image (örnek, opsiyonel)
      #   run: |
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker tag bluesense-api:latest yourdockerhub/bluesense-api:latest
      #     docker push yourdockerhub/bluesense-api:latest
